# Generated by Django 6.0 on 2025-12-15 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل العمليات', 'verbose_name_plural': 'سجلات العمليات'},
        ),
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name': 'إعدادات المتجر', 'verbose_name_plural': 'إعدادات المتجر'},
        ),
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': 'إعداد نظام', 'verbose_name_plural': 'إعدادات النظام'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المنفذ'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنفيذ'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='currency',
            field=models.CharField(default='SAR', max_length=10, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='store_name',
            field=models.CharField(max_length=150, verbose_name='اسم المتجر'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='المفتاح'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.TextField(verbose_name='القيمة'),
        ),
    ]
